# Based on oval_base_cplex.yaml with l2 norm specification and l2 norm cut settings
model:
  name: cifar_model_base
  path: models/oval/cifar_base.pth
data:
  dataset: CIFAR
  # Picked instances from models/oval/base_100.pkl (idxs: 13,17)
  pkl_path: models/oval/base_l2_norm_cut.pkl
  std: [0.225, 0.225, 0.225]
  mean: [0.485, 0.456, 0.406]
specification:
  norm: 2
  robustness_type: specify-target
attack:
  pgd_order: skip
solver:
  batch_size: 1024
  beta-crown:
    iteration: 20
    lr_beta: 0.03
    lr_decay: 0.96
bab:
  timeout: 3600
  branching:
    method: kfsb
    reduceop: min
    candidates: 10
  cut:
    enabled: True
    cplex_cuts: True
    bab_cut: True
    iteration: 200
    bab_iteration: 50 
    lr_beta: 0.01
    lr_decay: 0.8
