general:
  root_path: ../../vnncomp2024_benchmarks/benchmarks/lsnc
  csv_name: instances.csv
attack:
  pgd_order: skip
solver:
  batch_size: 500000
  min_batch_size_ratio: 0.1
  bound_prop_method: crown
  auto_enlarge_batch_size: True
bab:
  branching:
    method: sb
    input_split:
      enable: True
      split_hint: [0.]
      sb_coeff_thresh: 1.e-2
      sb_primary_spec: 0
      touch_zero_score: 0.1
      adv_check: -1
      reorder_bab: True
  clip_n_verify:
    clip_input_domain:
      enabled: True
      clip_type: complete