general:
  conv_mode: matrix
  sparse_alpha: false
  sparse_interm: false
  root_path: ../../vnncomp2023_benchmarks/benchmarks/ml4acopf
  csv_name: instances.csv
model:
  onnx_optimization_flags: ["remove_matmul_inplace"]
attack:
  pgd_order: before
  pgd_restarts: 100
  attack_tolerance: 0.0001
solver:
  batch_size: 512
  min_batch_size_ratio: 0.0
  alpha-crown:
    lr_alpha: 0.5
    lr_decay: 0.99
    iteration: 40
    disable_optimization: ['sin', 'cos']
  beta-crown:
    lr_alpha: 0.5
    iteration: 10
bab:
  pruning_in_iteration: False
  sort_domain_interval: 1
  branching:
    method: nonlinear
    candidates: 3
    nonlinear_split:
      num_branches: 2
      method: shortcut
      filter: true
