# Configuration file for running the nn4sys_2023 benchmark (pensieve models).
general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/nn4sys
  csv_name: instances.csv
  enable_incomplete_verification: false
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"  # Fix batch dimension in this onnx.
  cache_onnx_conversion: True
solver:
  batch_size: 256
  auto_enlarge_batch_size: true
  bound_prop_method: forward+crown
bab:
  initial_max_domains: 1000
  branching:
    method: sb
    input_split:
      enable: True
      # enable_clip_domains: True
      # reorder_bab: True
      adv_check: .inf
      sb_coeff_thresh: 0.1
attack:
  pgd_order: input_bab
