# Configuration file for running the vggnet16_2023 benchmark (all properties).
general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/vggnet16
  csv_name: instances.csv
  loss_reduction_func: max
  graph_optimizer: Customized("custom_graph_optimizer", "maxpool_to_relu")
  adhoc_tuning: Customized("custom_adhoc_tuning", "customized_vggnet16_tuning")
model:
  cache_onnx_conversion: True
solver:
  batch_size: 1  # Number of parallel domains to compute on GPU.
  bound_prop_method: dynamic-forward+backward
  forward:
    max_dim: 100
  crown:
    batch_size: 64
bab:
  branching:
    method: sb
    input_split:
      enable: True
attack:
  pgd_order: input_bab
