model:
  name: cifar_conv_small
  path: models/eran/cifar_conv_small_pgd.pth
data:
  dataset: CIFAR_ERAN
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 100
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  timeout: 120
