model:
  name: mnist_conv_small
  path: models/eran/mnist_conv_small_nat.pth
data:
  dataset: MNIST_ERAN
specification:
  epsilon: 0.12
attack:
  pgd_restarts: 100
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  timeout: 180
  branching:
    reduceop: max
