# Configuration file for running the ACASXu benchmark (all properties).
general:
  root_path: ../../vnncomp2021/benchmarks/acasxu  # Please clone the vnncomp2021 repo first as it contains the benchmark.
  csv_name: acasxu_instances.csv
  enable_incomplete_verification: False
  loss_reduction_func: max
data:
  num_outputs: 5
solver:
  batch_size: 1000  # Number of parallel domains to compute on GPU.
  bound_prop_method: crown
  beta-crown:
    iteration: 10  # Iterations for computing intermediate layer bounds.
  alpha-crown:
    iteration: 10
    share_alphas: True  # This produces slightly looser bounds, but faster.
bab:
  branching:
    method: naive  # Split on input space.
    candidates: 3
    input_split:
      enable: True
      enhanced_bound_prop_method: alpha-crown
      enhanced_bound_patience: 20
      enhanced_branching_method: sb
      attack_patience: 80
      sb_coeff_thresh: 0.01
attack:
  pgd_order: after
  pgd_restarts: 10000
