# Configuration file for running the rl_benchmarks benchmark (cartpole model).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/rl_benchmarks
  csv_name: instances.csv
  loss_reduction_func: max
  conv_mode: patches
data:
  num_outputs: 2
  start: 0
  end: 100
solver:
  batch_size: 100  # Number of parallel domains to compute on GPU.
  bound_prop_method: forward+backward
bab:
  branching:
    method: sb  # Split on input space.
    input_split:
      enable: True
attack:
  pgd_order: input_bab
