# Configuration file for running the cifar_biasfield benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/cifar_biasfield
  csv_name: instances.csv
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"
data:
  num_outputs: 10
solver:
  batch_size: 4  # Number of parallel domains to compute on GPU.
  bound_prop_method: crown
bab:
  branching:
    method: sb
    input_split:
      enable: True
      sb_coeff_thresh: 2.0
attack:
  pgd_order: after
  attack_mode: diversed_PGD
  pgd_steps: 20
  pgd_restarts: 300
  input_split:
    pgd_restarts: 30
    pgd_steps: 20
  input_split_check_adv:
    pgd_restarts: 10
    pgd_steps: 1
