# Configuration file for running the nn2sys_2022 benchmark (lindex models).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/nn4sys
  csv_name: instances.csv
  enable_incomplete_verification: false
  loss_reduction_func: max
  conv_mode: matrix
data:
  start: 0
  end: 24
solver:
  batch_size: 500000  # Number of parallel domains to compute on GPU.
  bound_prop_method: forward+backward
bab:
  initial_max_domains: 100000
  branching:
    method: sb  # Split on input space.
    input_split:
      enable: True
      adv_check: .inf
      sb_coeff_thresh: 0.1
attack:
  pgd_order: input_bab
