# Configuration file for running the reach_prob_density benchmark (all models except gcas).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/reach_prob_density
  csv_name: instances.csv
  loss_reduction_func: max
  conv_mode: matrix
solver:
  batch_size: 8192  # Number of parallel domains to compute on GPU.
  bound_prop_method: forward+backward
bab:
  sort_domain_interval: 1
  branching:
    method: sb
    input_split:
      enable: True
attack:
  pgd_order: input_bab
