# Configuration file for running the tllverifybench benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/tllverifybench
  csv_name: instances.csv
  conv_mode: matrix
specification:
  robustness_type: all-positive
data:
  num_outputs: 1
model:
  onnx_optimization_flags: merge_linear
solver:
  batch_size: 100  # Number of parallel domains to compute on GPU.
  bound_prop_method: forward+backward
bab:
  branching:
    method: naive
    input_split:
      enable: True
attack:
  pgd_order: before
