# Configuration file for running the vggnet16_2022 benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/vggnet16_2022
  csv_name: instances.csv
  loss_reduction_func: max
  adhoc_tuning: Customized("custom_adhoc_tuning", "customized_vggnet16_tuning")
data:
  num_outputs: 1000
solver:
  batch_size: 1  # Number of parallel domains to compute on GPU.
  bound_prop_method: dynamic-forward+backward
  forward:
    max_dim: 100
  crown:
    batch_size: 16
bab:
  branching:
    method: sb
    input_split:
      enable: True
attack:
  pgd_order: input_bab
